# Generated by Django 3.2.4 on 2021-11-24 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaysGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.game')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='played_by', through='profiles.PlaysGame', to='profiles.Game'),
        ),
    ]
