# Generated by Django 3.2.4 on 2021-07-06 06:24

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default=profiles.models.random_bio, max_length=150),
        ),
    ]
