# Generated by Django 3.2.4 on 2022-01-07 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20211202_0552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playsgame',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='plays_game', to='profiles.profile'),
        ),
    ]
