# Generated by Django 3.2.4 on 2021-07-12 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_twitchprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='display_name',
            field=models.CharField(default='hello', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='login',
            field=models.CharField(default='hello', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='profile_image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='user_id',
            field=models.CharField(default='hello', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='view_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
