# Generated by Django 3.2.4 on 2022-01-14 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_auto_20220114_1659'),
        ('profiles', '0004_alter_playsgame_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='socials',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='socials.socials'),
        ),
    ]
