# Generated by Django 3.2.4 on 2021-07-15 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_auto_20210712_1107'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=24)),
                ('channel_image_url', models.URLField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_profile', to='profiles.profile')),
            ],
        ),
    ]
