# Generated by Django 3.2.4 on 2022-01-20 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_auto_20220114_1659'),
        ('profiles', '0005_profile_socials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='socials',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='profile', to='socials.socials'),
        ),
    ]
