# Generated by Django 3.2.4 on 2021-07-24 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_youtubeprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='access_token',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='twitchprofile',
            name='refresh_token',
            field=models.CharField(default='hello', max_length=100),
            preserve_default=False,
        ),
    ]
