# Generated by Django 3.2.4 on 2021-07-25 06:39

from django.db import migrations, models
import profiles.models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20210724_1220'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='secret',
            field=models.CharField(default=profiles.models.random_twitch_secret, max_length=10),
        ),
    ]
