# Generated by Django 3.2.4 on 2021-07-25 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0008_twitchprofile_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='is_subscription_active',
            field=models.BooleanField(default=False),
        ),
    ]
