# Generated by Django 3.2.4 on 2021-07-25 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_twitchprofile_is_subscription_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
