# Generated by Django 3.2.4 on 2021-07-25 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_twitchprofile_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchprofile',
            name='profile_image_url',
        ),
    ]
