# Generated by Django 3.2.4 on 2021-07-25 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_twitchprofile_profile_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchprofile',
            name='access_token',
        ),
        migrations.RemoveField(
            model_name='twitchprofile',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='twitchprofile',
            name='refresh_token',
        ),
    ]
