# Generated by Django 3.2.4 on 2021-07-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_auto_20210725_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
