# Generated by Django 3.2.4 on 2021-07-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_rename_subscription_id_twitchprofile_stream_online_subscription_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitchprofile',
            name='stream_offline_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
