# Generated by Django 3.2.4 on 2021-07-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_twitchprofile_stream_offline_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_offline_subscription_id',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_online_subscription_id',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
