# Generated by Django 3.2.4 on 2021-07-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0016_auto_20210725_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_offline_subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_online_subscription_id',
            field=models.CharField(default='', max_length=100),
        ),
    ]
