# Generated by Django 3.2.4 on 2021-07-25 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0017_auto_20210725_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_offline_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='twitchprofile',
            name='stream_online_subscription_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
