# Generated by Django 3.2.4 on 2021-07-25 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20210725_1838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchprofile',
            name='is_subscription_active',
        ),
    ]
