# Generated by Django 3.2.4 on 2021-08-09 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_alter_following_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='following',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='profiles.profile'),
        ),
    ]
