# Generated by Django 3.2.4 on 2021-08-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_alter_following_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitchstream',
            name='game',
        ),
        migrations.RemoveField(
            model_name='twitchstream',
            name='twitch_profile',
        ),
        migrations.RemoveField(
            model_name='youtubeprofile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='TwitchProfile',
        ),
        migrations.DeleteModel(
            name='TwitchStream',
        ),
        migrations.DeleteModel(
            name='YouTubeProfile',
        ),
    ]
