# Generated by Django 3.2.4 on 2021-09-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20210830_1150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='trend_score',
            new_name='follower_count',
        ),
    ]
