version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: <TASK_DEFINITION>
        LoadBalancerInfo:
          ContainerName: "plx-dev"
          ContainerPort: 80
        PlatformVersion: "LATEST"
        NetworkConfiguration:
          AwsvpcConfiguration:
            Subnets: ["subnet-091fa93896a236c59", "subnet-04295b61608393f4d"]
            SecurityGroups: ["sg-0e46a6542f88c1747"]
            AssignPublicIp: "ENABLED"
