version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - REPOSITORY_URI=$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - DATE=$(date +"%Y%m%d_%H%M%S")
      - echo Build started on $(date +"%Y%m%d_%H%M%S")
      - echo Building the Docker images...
      - DAPHNE_URI_T=$REPOSITORY_URI:daphne_$DATE
      - NGINX_URI_T=$REPOSITORY_URI:nginx_$DATE
      - CELERY_URI_T=$REPOSITORY_URI:celery_$DATE
      - LOL_CELERY_URI_T=$REPOSITORY_URI:lol_celery_$DATE

      - docker-compose build
      - docker tag daphne:latest $DAPHNE_URI_T
      - docker tag nginx:latest $NGINX_URI_T
      - docker tag celery:latest $CELERY_URI_T
      - docker tag lol_celery:latest $LOL_CELERY_URI_T
      # - docker tag $IMAGE_REPO_NAME:$IMAGE_TAG $REPOSITORY_URI/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on $(date +"%Y%m%d_%H%M%S")
      - echo Pushing the Docker images...
      - docker image push --all-tags $DAPHNE_URI_T
      - docker image push --all-tags $NGINX_URI_T
      - docker image push --all-tags $CELERY_URI_T
      - docker image push --all-tags $LOL_CELERY_URI_T

      - sed -i 's@<NGINX_IMAGE>@'"$NGINX_URI_T"'@' aws_resources/taskdef_main.json
      - sed -i 's@<DAPHNE_IMAGE>@'"$DAPHNE_URI_T"'@' aws_resources/taskdef_main.json
      - sed -i 's@<CELERY_IMAGE>@'"$CELERY_URI_T"'@' aws_resources/taskdef_main.json

      - cat aws_resources/taskdef_main.json

      - printf '[{"name":"plx-daphne","imageUri":"%s"},{"name":"plx-nginx","imageUri":"%s"},{"name":"plx-celery","imageUri":"%s"}]' $DAPHNE_URI_T $NGINX_URI_T $CELERY_URI_T > imagedefinitions1.json
      - printf '[{"name":"plx-lol-celery","imageUri":"%s"}]' $LOL_CELERY_URI_T  > imagedefinitions2.json

artifacts:
  files:
    - imagedefinitions1.json
    - imagedefinitions2.json
    - aws_resources/taskdef_main.json
    - appspec.yml
  name: buildartifacts
