version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "python manage.py migrate --noinput &&
      python manage.py collectstatic --noinput &&
      daphne -b 0.0.0.0 -p 8000 shinobi.asgi:application"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    restart: on-failure

  nginx:
    build: ./nginx.dev
    ports:
      - "80:80"
    restart: on-failure
    volumes:
      - ./static:/usr/src/app/static
    depends_on:
      - api

  chat:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: daphne -b 0.0.0.0 -p 9001 shinobi.asgi:application
    volumes:
      - .:/usr/src/app
    ports:
      - "9001:9001"
    restart: on-failure
    depends_on:
      - api

  celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A shinobi worker -l INFO --uid=nobody --gid=nogroup -Q celery
    volumes:
      - .:/usr/src/app
    restart: on-failure
    depends_on:
      - api

  scheduler_celery:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: celery -A shinobi beat
    volumes:
      - .:/usr/src/app
    restart: on-failure
    depends_on:
      - api

volumes:
  static:
