# Generated by Django 3.2.4 on 2021-08-30 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='total_users',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='monthlyanalytics',
            name='total_users',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weeklyanalytics',
            name='total_users',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
