# Generated by Django 3.2.4 on 2021-11-20 15:55

from django.db import migrations, models
import shinobi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyAnalytics',
        ),
        migrations.DeleteModel(
            name='WeeklyAnalytics',
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='date',
            field=models.DateField(default=shinobi.utils.now_date, primary_key=True, serialize=False),
        ),
    ]
