# Generated by Django 3.2.4 on 2021-11-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20211120_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyanalytics',
            name='total_clips',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='active_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='new_users',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailyanalytics',
            name='total_users',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
