# Generated by Django 3.2.4 on 2022-02-01 06:21

from django.db import migrations, models
import shinobi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_auto_20211213_0614'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyAnalytics',
            fields=[
                ('date', models.DateField(default=shinobi.utils.now_date, primary_key=True, serialize=False)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_clips_m', models.PositiveIntegerField(default=0)),
                ('total_clips_w', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WeeklyAnalytics',
            fields=[
                ('date', models.DateField(default=shinobi.utils.now_date, primary_key=True, serialize=False)),
                ('new_users', models.PositiveIntegerField(default=0)),
                ('active_users', models.PositiveIntegerField(default=0)),
                ('total_users', models.PositiveIntegerField(default=0)),
                ('total_clips_m', models.PositiveIntegerField(default=0)),
                ('total_clips_w', models.PositiveIntegerField(default=0)),
                ('total_views', models.PositiveBigIntegerField(default=0)),
            ],
        ),
    ]
