# Generated by Django 3.2.4 on 2021-08-25 07:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0024_alter_following_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoLProfile',
            fields=[
                ('puuid', models.CharField(max_length=78, primary_key=True, serialize=False)),
                ('account_id', models.CharField(max_length=56)),
                ('summoner_id', models.CharField(max_length=63)),
                ('active', models.BooleanField(default=False)),
                ('updating', models.BooleanField(default=False)),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lol_profile', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='ParticipantStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assists', models.PositiveSmallIntegerField()),
                ('deaths', models.PositiveSmallIntegerField()),
                ('kills', models.PositiveSmallIntegerField()),
                ('items', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('B', 'Blue'), ('R', 'Red')], max_length=1)),
                ('win', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('champion_key', models.CharField(max_length=15)),
                ('role', models.CharField(max_length=15)),
                ('stats', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='participant', to='league_of_legends.participantstats')),
                ('summoner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='league_of_legends.lolprofile')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participants', to='league_of_legends.team')),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.PositiveBigIntegerField(primary_key=True, serialize=False)),
                ('creation', models.DateTimeField()),
                ('mode', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=3)),
                ('blue_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='b_match', to='league_of_legends.team')),
                ('red_team', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='r_match', to='league_of_legends.team')),
            ],
        ),
    ]
