# Generated by Django 3.2.4 on 2021-10-13 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantstats',
            name='double_kills',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstats',
            name='penta_kills',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstats',
            name='quadra_kills',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstats',
            name='spell_casts',
            field=models.JSONField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstats',
            name='total_damage_dealt',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='participantstats',
            name='triple_kills',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
