# Generated by Django 3.2.4 on 2021-09-15 16:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('league_of_legends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerifyLolProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summoner_name', models.CharField(max_length=16)),
                ('old_profile_icon', models.PositiveSmallIntegerField(default=0)),
                ('new_profile_icon', models.PositiveSmallIntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='verify_lol_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
