# Generated by Django 3.2.4 on 2021-08-25 07:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='creation',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
