# Generated by Django 3.2.4 on 2021-08-25 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0002_team_creation'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolprofile',
            name='name',
            field=models.CharField(default='Kalturi', max_length=16),
            preserve_default=False,
        ),
    ]
