# Generated by Django 3.2.4 on 2021-09-15 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0002_verifylolprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='lolprofile',
            name='region',
            field=models.CharField(choices=[('BR1', 'BR1'), ('EUN1', 'EUN1'), ('EUW1', 'EUW1'), ('JP1', 'JP1'), ('KR', 'KR'), ('LA1', 'LA1'), ('LA2', 'LA2'), ('NA1', 'NA1'), ('OC1', 'OC1'), ('TR1', 'TR1'), ('RU', 'RU')], default='NA1', max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='verifylolprofile',
            name='region',
            field=models.CharField(choices=[('BR1', 'BR1'), ('EUN1', 'EUN1'), ('EUW1', 'EUW1'), ('JP1', 'JP1'), ('KR', 'KR'), ('LA1', 'LA1'), ('LA2', 'LA2'), ('NA1', 'NA1'), ('OC1', 'OC1'), ('TR1', 'TR1'), ('RU', 'RU')], default='NS\x08A1', max_length=4),
            preserve_default=False,
        ),
    ]
