# Generated by Django 3.2.4 on 2021-08-25 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0003_lolprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='summoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='league_of_legends.lolprofile'),
        ),
    ]
