# Generated by Django 3.2.4 on 2021-12-23 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0003_alter_lolprofile_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='blue_team',
        ),
        migrations.RemoveField(
            model_name='match',
            name='red_team',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='stats',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='summoner',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='team',
        ),
        migrations.RemoveField(
            model_name='verifylolprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='LolProfile',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
        migrations.DeleteModel(
            name='ParticipantStats',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='VerifyLolProfile',
        ),
    ]
