# Generated by Django 3.2.4 on 2021-08-27 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0004_alter_participant_summoner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='champion_key',
        ),
        migrations.AddField(
            model_name='participant',
            name='champion_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='region',
            field=models.CharField(max_length=5),
        ),
    ]
