# Generated by Django 3.2.4 on 2021-08-27 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0005_auto_20210827_1304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='champion_id',
            new_name='champion_key',
        ),
    ]
