# Generated by Django 3.2.4 on 2021-08-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0006_rename_champion_id_participant_champion_key'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='champion_key',
            new_name='champion_id',
        ),
    ]
