# Generated by Django 3.2.4 on 2021-08-29 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('league_of_legends', '0007_rename_champion_key_participant_champion_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='champion_id',
            new_name='champion_key',
        ),
    ]
