# Generated by Django 3.2.4 on 2022-01-07 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('f', 'follow'), ('c', 'clip')], default='f', max_length=1),
        ),
    ]
