# Generated by Django 3.2.4 on 2022-01-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('f', 'follow'), ('c', 'clip'), ('l', 'like'), ('rp', 'repost')], max_length=2),
        ),
    ]
