# Generated by Django 3.2.4 on 2021-11-19 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(default=datetime.datetime.today)),
                ('created_datetime', models.DateTimeField(default=datetime.datetime(2021, 11, 19, 16, 57, 9, 883824, tzinfo=utc))),
                ('title', models.CharField(max_length=80)),
                ('url', models.URLField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clips', to='profiles.game')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clip_uploads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
