# Generated by Django 3.2.4 on 2021-11-21 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0003_auto_20211120_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='upload_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ClipToUpload',
        ),
    ]
