# Generated by Django 3.2.4 on 2021-11-22 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0005_alter_clip_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='height_to_width_ratio',
            field=models.FloatField(default=1.0),
            preserve_default=False,
        ),
    ]
