# Generated by Django 3.2.4 on 2021-11-23 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0006_clip_height_to_width_ratio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='title',
        ),
    ]
