# Generated by Django 3.2.4 on 2021-11-23 15:57

import clips.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0008_alter_clip_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='id',
            field=models.CharField(default=clips.models.generate_random_id, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(limit_value=12)]),
        ),
    ]
