# Generated by Django 3.2.4 on 2021-11-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0011_clip_share_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='title',
            field=models.CharField(default='Random test video', max_length=40),
            preserve_default=False,
        ),
    ]
