# Generated by Django 3.2.4 on 2021-11-29 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0013_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='compressed_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clip_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='clips.clip'),
        ),
    ]
