# Generated by Django 3.2.4 on 2021-11-29 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0014_auto_20211129_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='reported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clip_reports', to='authentication.user'),
        ),
    ]
