# Generated by Django 3.2.4 on 2021-11-30 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0015_alter_report_reported_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clip',
            name='height_to_width_ratio',
        ),
        migrations.AddField(
            model_name='clip',
            name='height',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clip',
            name='width',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
