# Generated by Django 3.2.4 on 2021-12-06 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0016_auto_20211130_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='clip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.clip'),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('clip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clips.clip')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='clip',
            name='viewed_by',
            field=models.ManyToManyField(blank=True, related_name='viewed_clips', through='clips.View', to=settings.AUTH_USER_MODEL),
        ),
    ]
