# Generated by Django 3.2.4 on 2021-12-06 09:48

from django.db import migrations, models
import django.utils.timezone
import shinobi.utils


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0017_auto_20211206_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='view',
            name='created',
        ),
        migrations.AddField(
            model_name='view',
            name='created_date',
            field=models.DateField(default=shinobi.utils.now_date),
        ),
        migrations.AddField(
            model_name='view',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
