# Generated by Django 3.2.4 on 2021-12-13 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0018_auto_20211206_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='uploaded_from',
            field=models.CharField(choices=[('M', 'Mobile'), ('W', 'Web')], default='M', max_length=1),
            preserve_default=False,
        ),
    ]
