# Generated by Django 3.2.4 on 2021-12-24 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0021_alter_clip_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='clip',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_by',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='game',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='liked_by',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='title',
        ),
        migrations.RemoveField(
            model_name='clip',
            name='uploader',
        ),
        migrations.DeleteModel(
            name='Like',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
