# Generated by Django 3.2.4 on 2022-01-07 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0022_auto_20211224_0606'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='view',
            options={'ordering': ['-created_datetime']},
        ),
    ]
