# Generated by Django 3.2.4 on 2022-01-13 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0023_alter_view_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='view_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
