# Generated by Django 3.2.4 on 2022-01-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0024_clip_view_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='duration',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
