# Generated by Django 3.2.4 on 2022-02-08 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0025_clip_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='job_id',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
