# Generated by Django 3.2.4 on 2022-02-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0026_clip_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='thumbnail',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
