# Generated by Django 3.2.4 on 2022-02-28 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0027_clip_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='clip',
            name='file_uuid',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clip',
            name='upload_path',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
