# Generated by Django 3.2.4 on 2022-02-28 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0029_rename_compressed_verified_clip_convert_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='upload_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
