# Generated by Django 3.2.4 on 2022-02-28 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clips', '0030_alter_clip_upload_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clip',
            name='url',
            field=models.URLField(blank=True, null=True, unique=True),
        ),
    ]
