# Generated by Django 3.2.4 on 2021-07-20 05:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_message_chat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
