# Generated by Django 3.2.4 on 2021-09-27 07:11

from django.db import migrations, models
import django.db.models.deletion
import socials.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitchProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20)),
                ('login', models.CharField(max_length=25)),
                ('display_name', models.CharField(max_length=25)),
                ('view_count', models.PositiveBigIntegerField(default=0)),
                ('secret', models.CharField(default=socials.models.random_twitch_secret, max_length=10)),
                ('stream_online_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stream_offline_subscription_id', models.CharField(blank=True, max_length=100, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='twitch_profile', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=24)),
                ('channel_image_url', models.URLField(blank=True, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='youtube_profile', to='profiles.profile')),
            ],
        ),
        migrations.CreateModel(
            name='TwitchStream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stream_id', models.CharField(max_length=100)),
                ('title', models.CharField(blank=True, max_length=140, null=True)),
                ('thumbnail_url', models.URLField(blank=True, null=True)),
                ('is_streaming', models.BooleanField(default=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='twitch_streams', to='profiles.game')),
                ('twitch_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_stream', to='socials.twitchprofile')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('b', 'business'), ('m', 'media_creator'), ('p', 'personal')], default='p', max_length=1)),
                ('username', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instagram_profile', to='profiles.profile')),
            ],
        ),
    ]
