# Generated by Django 3.2.4 on 2021-08-31 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitchstream',
            name='title',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AlterField(
            model_name='twitchstream',
            name='twitch_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='twitch_stream', to='socials.twitchprofile'),
        ),
    ]
