# Generated by Django 3.2.4 on 2021-08-31 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20210830_1150'),
        ('socials', '0002_auto_20210831_0915'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('b', 'business'), ('m', 'media_creator'), ('p', 'personal')], default='p', max_length=1)),
                ('username', models.CharField(max_length=30)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='instagram_profile', to='profiles.profile')),
            ],
        ),
    ]
