# Generated by Django 3.2.4 on 2021-12-07 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0002_auto_20211002_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youtubeprofile',
            name='channel_image_url',
        ),
    ]
