# Generated by Django 3.2.4 on 2022-01-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0003_remove_youtubeprofile_channel_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube', models.CharField(blank=True, max_length=24, null=True)),
                ('instagram', models.CharField(blank=True, max_length=30, null=True)),
                ('twitch', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='twitchprofile',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='youtubeprofile',
            name='profile',
        ),
        migrations.DeleteModel(
            name='InstagramProfile',
        ),
        migrations.DeleteModel(
            name='TwitchProfile',
        ),
        migrations.DeleteModel(
            name='YouTubeProfile',
        ),
    ]
