# Generated by Django 3.2.4 on 2022-02-10 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0004_auto_20220114_1659'),
    ]

    operations = [
        migrations.AddField(
            model_name='socials',
            name='custom_title',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='socials',
            name='custom_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
