# Generated by Django 3.2.4 on 2022-02-16 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socials', '0005_auto_20220210_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socials',
            name='custom_title',
        ),
    ]
