# Generated by Django 3.2.4 on 2021-11-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_uploading_clip',
            field=models.BooleanField(default=False),
        ),
    ]
