# Generated by Django 3.2.4 on 2021-06-20 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.URLField(blank=True, null=True),
        ),
    ]
