# Generated by Django 3.2.4 on 2021-11-23 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_is_uploading_clip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_uploading_clip',
        ),
    ]
