# Generated by Django 3.2.4 on 2021-12-12 09:46

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_remove_user_is_uploading_clip'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='action_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='last_action_date',
            field=models.DateField(default=authentication.models.today_date),
        ),
    ]
