# Generated by Django 3.2.4 on 2021-07-21 05:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_user_last_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_inactive',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
