# Generated by Django 3.2.4 on 2021-09-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_last_inactive_user_last_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_active',
            new_name='last_online',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='active',
            new_name='online',
        ),
    ]
