# Generated by Django 3.2.4 on 2021-09-01 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20210901_0746'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_online',
            new_name='last_close',
        ),
    ]
