# Generated by Django 3.2.4 on 2021-12-24 06:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0003_auto_20211202_0552'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('clips', '0022_auto_20211224_0606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.CharField(default=feed.models.generate_random_id, max_length=12, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(limit_value=12)])),
                ('created_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=80)),
                ('share_count', models.PositiveIntegerField(default=0)),
                ('clip', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clip_post', to='clips.clip')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='game_posts', to='profiles.game')),
                ('liked_by', models.ManyToManyField(blank=True, related_name='liked_posts', through='feed.Like', to=settings.AUTH_USER_MODEL)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_not_playing', models.BooleanField(default=False)),
                ('is_not_game_clip', models.BooleanField(default=False)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='feed.post')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='post_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='feed.post'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
