# Generated by Django 3.2.4 on 2022-01-07 07:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created_datetime']},
        ),
        migrations.AddField(
            model_name='like',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='report',
            name='created_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
