# Generated by Django 3.2.4 on 2022-01-08 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20220107_0704'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='uploader',
            new_name='posted_by',
        ),
        migrations.AddField(
            model_name='post',
            name='is_repost',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='feed.post'),
        ),
    ]
