# Generated by Django 3.2.4 on 2022-01-08 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_playsgame_profile'),
        ('clips', '0023_alter_view_options'),
        ('feed', '0003_auto_20220108_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='clip',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clip_post', to='clips.clip'),
        ),
        migrations.AlterField(
            model_name='post',
            name='game',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='game_posts', to='profiles.game'),
        ),
        migrations.AlterField(
            model_name='post',
            name='repost',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reposts', to='feed.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
