# Generated by Django 3.2.4 on 2022-02-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_auto_20220205_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='country_code',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
