# Generated by Django 3.2.4 on 2022-03-05 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_post_country_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='fetch_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
