# Generated by Django 3.2.4 on 2022-01-12 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdate',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
