# Generated by Django 3.2.4 on 2022-01-13 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ux', '0002_appupdate_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='appupdate',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
